base_url = "https://repro-hpc.github.io/"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

[markdown]
highlight_code = false
highlight_theme = "css"
smart_punctuation = true

[extra]
footer_text = "This website is built using [Zola](https://www.getzola.org) and the [Academic Workshop](http://github.com/aterenin/academic-workshop/) theme, which is [designed to last](https://jeffhuang.com/designed_to_last/)."
title = {title = "REPRO-HPC", subtitles = ["1ˢᵗ Workshop in Sustainable Practices for Reproducibility in HPC", "hosted at ISC26 - 26th June 2026"]}
# banner = {extension = "jpg", size = "fixed", fade = true}
banner = {extension = "jpg", size = "cover", fade = true}
buttons = [{name="Home", url = "/"},{name = "Call for Contributions", url = "#call-for-contributions"}, {name="Program", url="#program"}, {name="Committees",url="#committees"}]
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10
header_pages = [{name = "Home", url = "/#home"}]
